// Code generated by protoc-gen-go. DO NOT EDIT.
// source: common.proto

/*
Package api is a generated protocol buffer package.

It is generated from these files:
	common.proto
	timesheet.proto
	user.proto

It has these top-level messages:
	SimpleResponse
	SearchOptions
	ClockRequest
	TimeSheetRequest
	TSStatusResponse
	TimeEntry
	EmailOrId
	LockUserRequest
	DisableUserRequest
	DeleteUserRequest
	DeleteUserResponse
	GetUserRequest
	GetUsersRequest
	User
*/
package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SimpleResponse struct {
	IsSuccess bool   `protobuf:"varint,1,opt,name=IsSuccess" json:"IsSuccess,omitempty"`
	Message   string `protobuf:"bytes,2,opt,name=Message" json:"Message,omitempty"`
}

func (m *SimpleResponse) Reset()                    { *m = SimpleResponse{} }
func (m *SimpleResponse) String() string            { return proto.CompactTextString(m) }
func (*SimpleResponse) ProtoMessage()               {}
func (*SimpleResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *SimpleResponse) GetIsSuccess() bool {
	if m != nil {
		return m.IsSuccess
	}
	return false
}

func (m *SimpleResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type SearchOptions struct {
	Query   string `protobuf:"bytes,1,opt,name=Query" json:"Query,omitempty"`
	Page    uint32 `protobuf:"varint,2,opt,name=Page" json:"Page,omitempty"`
	PerPage uint32 `protobuf:"varint,3,opt,name=PerPage" json:"PerPage,omitempty"`
}

func (m *SearchOptions) Reset()                    { *m = SearchOptions{} }
func (m *SearchOptions) String() string            { return proto.CompactTextString(m) }
func (*SearchOptions) ProtoMessage()               {}
func (*SearchOptions) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *SearchOptions) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

func (m *SearchOptions) GetPage() uint32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *SearchOptions) GetPerPage() uint32 {
	if m != nil {
		return m.PerPage
	}
	return 0
}

func init() {
	proto.RegisterType((*SimpleResponse)(nil), "api.SimpleResponse")
	proto.RegisterType((*SearchOptions)(nil), "api.SearchOptions")
}

func init() { proto.RegisterFile("common.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 162 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x49, 0xce, 0xcf, 0xcd,
	0xcd, 0xcf, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4e, 0x2c, 0xc8, 0x54, 0xf2, 0xe0,
	0xe2, 0x0b, 0xce, 0xcc, 0x2d, 0xc8, 0x49, 0x0d, 0x4a, 0x2d, 0x2e, 0xc8, 0xcf, 0x2b, 0x4e, 0x15,
	0x92, 0xe1, 0xe2, 0xf4, 0x2c, 0x0e, 0x2e, 0x4d, 0x4e, 0x4e, 0x2d, 0x2e, 0x96, 0x60, 0x54, 0x60,
	0xd4, 0xe0, 0x08, 0x42, 0x08, 0x08, 0x49, 0x70, 0xb1, 0xfb, 0xa6, 0x16, 0x17, 0x27, 0xa6, 0xa7,
	0x4a, 0x30, 0x29, 0x30, 0x6a, 0x70, 0x06, 0xc1, 0xb8, 0x4a, 0xc1, 0x5c, 0xbc, 0xc1, 0xa9, 0x89,
	0x45, 0xc9, 0x19, 0xfe, 0x05, 0x25, 0x99, 0xf9, 0x79, 0xc5, 0x42, 0x22, 0x5c, 0xac, 0x81, 0xa5,
	0xa9, 0x45, 0x95, 0x60, 0x43, 0x38, 0x83, 0x20, 0x1c, 0x21, 0x21, 0x2e, 0x96, 0x00, 0x98, 0x6e,
	0xde, 0x20, 0x30, 0x1b, 0x64, 0x68, 0x40, 0x6a, 0x11, 0x58, 0x98, 0x19, 0x2c, 0x0c, 0xe3, 0x26,
	0xb1, 0x81, 0x9d, 0x6a, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x2f, 0x72, 0xdc, 0xc6, 0xba, 0x00,
	0x00, 0x00,
}
